# version 0.0.1 
types:   
        - deploy 
# Build teonet docker image and upload it to Docker HUB 
build_teonet_image:   
        type: deploy   
        tags:       
                - docker_image_build   
        script:     
                - docker build -t gitlab.ksproject.org:5000/maxtests/web:$CI_BUILD_TAG -f docker/Dockerfile .     
                - docker push gitlab.ksproject.org:5000/maxtests/web:$CI_BUILD_TAG     
        # update latest     
                - docker tag gitlab.ksproject.org:5000/maxtests/web:$CI_BUILD_TAG gitlab.ksproject.org:5000/maxtests/web:latest     
                - docker push gitlab.ksproject.org:5000/maxtests/web:latest   
        only:     
                - tags  
